# This file is part of LibToHttp.
# https://github.com/Utsav2/LibToHttp

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2015, Utsav Shah <ukshah2@illinois.edu>

language: python

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
